//
// Generated file, do not edit! Created by nedtool 5.7 from MyMessage.msg.
//

#ifndef __MYMESSAGE_M_H
#define __MYMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0507
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <bitset>
typedef  std::bitset<8> bits;
// }}

/**
 * Class generated from <tt>MyMessage.msg:25</tt> by nedtool.
 * <pre>
 * packet MyMessage
 * {
 *     \@customize(true);  // see the generated C++ header for more info
 *     int Seq_Num;
 *     int M_Type;
 *     string M_Payload;
 *     bits mycheckbits;
 * }
 * </pre>
 *
 * MyMessage_Base is only useful if it gets subclassed, and MyMessage is derived from it.
 * The minimum code to be written for MyMessage is the following:
 *
 * <pre>
 * class MyMessage : public MyMessage_Base
 * {
 *   private:
 *     void copy(const MyMessage& other) { ... }

 *   public:
 *     MyMessage(const char *name=nullptr, short kind=0) : MyMessage_Base(name,kind) {}
 *     MyMessage(const MyMessage& other) : MyMessage_Base(other) {copy(other);}
 *     MyMessage& operator=(const MyMessage& other) {if (this==&other) return *this; MyMessage_Base::operator=(other); copy(other); return *this;}
 *     virtual MyMessage *dup() const override {return new MyMessage(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from MyMessage_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(MyMessage)
 * </pre>
 */

#include "M_Type.h"
class MyMessage_Base : public ::omnetpp::cPacket
{
  protected:
    int messageId;
    double sendingTime;
    std::string M_Payload;
    char Trailer;
    int Seq_Num;
    M_Type M_Type_Value;
    bool isModified ;
    bits mycheckbits;
    bool haveData;

  private:
    void copy(const MyMessage_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyMessage_Base&);
    // make constructors protected to avoid instantiation

    // make assignment operator protected to force the user override it
    MyMessage_Base& operator=(const MyMessage_Base& other);

  public:
    MyMessage_Base(const char *name=nullptr, short kind=0);
    MyMessage_Base(const MyMessage_Base& other);
    virtual ~MyMessage_Base();
    virtual MyMessage_Base *dup() const override {
        return new MyMessage_Base(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSeq_Num() const;
    virtual void setSeq_Num(int Seq_Num);
    virtual M_Type getM_Type() const;
    virtual void setM_Type(M_Type M_Type_in);
    virtual const char * getM_Payload() const;
    virtual void setM_Payload(const char * M_Payload);
    virtual bits& getMycheckbits();
    virtual const bits& getMycheckbits() const {return const_cast<MyMessage_Base*>(this)->getMycheckbits();}
    virtual void setMycheckbits(const bits& mycheckbits);

    virtual int getMessageId() const{return (this)->messageId;}
    virtual void setMessageId(int MessageId){(this)->messageId = MessageId;}


    virtual double getSendingTime() const {return (this)->sendingTime;}
    virtual void setSendingTime(double Time){(this)->sendingTime = Time;}


    virtual char getTrailer() const {return (this)->Trailer;}
    virtual void setTrailer(char CRC){(this)->Trailer = CRC;}

    virtual bool getIsModified() const {return (this)->isModified;}
    virtual void setIsModified(bool isModified_input){(this)->isModified = isModified_input;}

    virtual bool gethaveData() const {return (this)->haveData;}
    virtual void sethaveData(bool haveData_Input){(this)->haveData = haveData_Input;}
};


#endif // ifndef __MYMESSAGE_M_H

